/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication45;

import java.awt.Color;

/**
 *
 * @author PERSO
 */
public class NewJFrame extends javax.swing.JFrame {
    public static boolean check = false;
   public int INT11;
   public int INT21;
   public int INT31;
   public int INT41;
   public int INT51;
   public int INT61;
   public int INT71;
   public int INT81;
   public int INT91;
   public static int ver;
   public int INT1;
   public int INT2;
   public int INT3;
   public int INT4;
   public int INT5;
   public int INT6;
   public int INT7;
   public int INT8;
   public int INT9;
   public static int VicX;
   public static int VicO;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setEnabled(false);
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setEnabled(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setEnabled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jButton10.setBackground(new java.awt.Color(102, 255, 102));
        jButton10.setText("START");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));

        jButton11.setText("RESTART");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("MORPION");

        jLabel5.setText("Victoire X:");

        jLabel6.setText("Victoire O:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButton10)
                .addGap(40, 40, 40)
                .addComponent(jButton11)
                .addGap(0, 224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(263, 263, 263))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(false);
        jButton10.setBackground(Color.white);
        /*---------------------------------------------------------------*/

    }//GEN-LAST:event_jButton10ActionPerformed
    private void nextPart()
    {
//                   this.dispose();
//                   NewJFrame bf = new NewJFrame();
//                   bf.setVisible(true); 
//                   jPanel1.setEnabled(true);
                jPanel1.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(false);
        jButton10.setBackground(Color.white);
        INT1=-1;
        INT2=-1;
        INT3=-1;
        INT4=-1;
        INT5=-1;
        INT6=-1;
        INT7=-1;
        INT8=-1;
        INT9=-1;
        INT11=-1;
        INT21=-1;
        INT31=-1;
        INT41=-1;
        INT51=-1;
        INT61=-1;
        INT71=-1;
        INT81=-1;
        INT91=-1;
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        
        jButton1.setBackground(Color.white);
        jButton2.setBackground(Color.white);
        jButton3.setBackground(Color.white);
        jButton4.setBackground(Color.white);
        jButton5.setBackground(Color.white);
        jButton6.setBackground(Color.white);
        jButton7.setBackground(Color.white);
        jButton8.setBackground(Color.white);
        jButton9.setBackground(Color.white);
        //jButton1.setBackground(Color.decode(FFFFFF));
    }
    private void VerifXVictory()
    {
                 if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
                                      jButton1.setEnabled(false);
                                      jButton2.setEnabled(false);
                   jButton3.setEnabled(false);
                   jButton4.setEnabled(false);
                   jButton5.setEnabled(false);
                   jButton6.setEnabled(false);
                   jButton7.setEnabled(false);
                   jButton8.setEnabled(false);
                   jButton9.setEnabled(false);
                   
               }
    }
    private void VerifOVictory()
    {
                      if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
                                      jButton1.setEnabled(false);
                   jButton2.setEnabled(false);
                   jButton3.setEnabled(false);
                   jButton4.setEnabled(false);
                   jButton5.setEnabled(false);
                   jButton6.setEnabled(false);
                   jButton7.setEnabled(false);
                   jButton8.setEnabled(false);
                   jButton9.setEnabled(false);
              }  
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        ver++;
        if(ver%2==0)
        {
            INT21=1;
            jButton2.setText("X");
            jButton2.setBackground(Color.pink);
        }
        else
        {
            INT2=1;
            jButton2.setText("O");
            jButton2.setBackground(Color.CYAN);
        }
        jButton2.setEnabled(false);
        
    /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
                if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                    ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT41=1;
            jButton4.setText("X");
            jButton4.setBackground(Color.pink);
        }
        else
        {
            INT4=1;
            jButton4.setText("O");
            jButton4.setBackground(Color.CYAN);
        }
        jButton4.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
                               if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                ver++;
        if(ver%2==0)
        {
            INT71=1;
            jButton7.setText("X");
            jButton7.setBackground(Color.pink);
        }
        else
        {
            INT7=1;
            jButton7.setText("O");
            jButton7.setBackground(Color.CYAN);
        }
        jButton7.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
              if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT11=1;
            jButton1.setText("X");
            jButton1.setBackground(Color.pink);
        }
        else
        {
            INT1=1;
            jButton1.setText("O");
            jButton1.setBackground(Color.CYAN);
        }
        jButton1.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
              if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT51=1;
            jButton5.setText("X");
            jButton5.setBackground(Color.pink);
        }
        else
        {
            INT5=1;
            jButton5.setText("O");
            jButton5.setBackground(Color.CYAN);
        }
        jButton5.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
               if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
                VerifXVictory();
                VerifOVictory();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                ver++;
        if(ver%2==0)
        {
            INT81=1;
            jButton8.setText("X");
            jButton8.setBackground(Color.pink);
        }
        else
        {
            INT8=1;
            jButton8.setText("O");
            jButton8.setBackground(Color.CYAN);
        }
        jButton8.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
               if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT31=1;
            jButton3.setText("X");
            jButton3.setBackground(Color.pink);
        }
        else
        {
            INT3=1;
            jButton3.setText("O");
            jButton3.setBackground(Color.CYAN);
        }
        jButton3.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
             if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
                VerifXVictory();
                VerifOVictory();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT61=1;
            jButton6.setText("X");
            jButton6.setBackground(Color.pink);
        }
        else
        {
            INT6=1;
            jButton6.setText("O");
            jButton6.setBackground(Color.CYAN);
        }
        jButton6.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
              if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                ver++;
                
        if(ver%2==0)
        {
            INT91=1;
            jButton9.setText("X");
            jButton9.setBackground(Color.pink);
        }
        else
        {
            INT9=1;
            jButton9.setText("O");
            jButton9.setBackground(Color.CYAN);
        }
        jButton9.setEnabled(false);
            /*-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/    
                if(jButton1.isEnabled()==check && jButton2.isEnabled()==check &&jButton3.isEnabled()==check &&jButton4.isEnabled()==check &&jButton5.isEnabled()==check &&jButton6.isEnabled()==check
             &&jButton7.isEnabled()==check && jButton8.isEnabled()==check &&jButton9.isEnabled()==check )
               {
                if(INT21 == 1 && INT51==1 && INT91==1 || INT21==1 && INT41==1 && INT71==1 || INT21==1 && INT11==1 && INT31==1 || 
                       INT41==1 && INT51==1 && INT61==1 || INT11==1 && INT51==1 && INT81==1 || INT31==1 && INT51==1 && INT71==1 ||
                      INT31==1 && INT61==1 && INT91==1 || INT71==1 && INT81==1 && INT91==1)
               {
                   jLabel1.setText("Joueur X VAINQUEUR");
                   ++VicX;
                   jLabel5.setText("Victoire X:"+VicX);
               }
                else   if(INT2 == 1 && INT5==1 && INT9==1 || INT2==1 && INT4==1 && INT7==1 || INT2==1 && INT1==1 && INT3==1 || 
                       INT4==1 && INT5==1 && INT6==1 || INT1==1 && INT5==1 && INT8==1 || INT3==1 && INT5==1 && INT7==1 ||
                      INT3==1 && INT6==1 && INT9==1 || INT7==1 && INT8==1 && INT9==1)
              {
                   jLabel3.setText("Joueur O VAINQUEUR");
                   ++VicO;
                   jLabel6.setText("Victoire O:"+VicO);
              }
                else{
                   jLabel2.setText("Match NULL");
                }
                                      jButton11.setEnabled(true);
                   jButton11.setBackground(Color.getHSBColor(180,100,40));
               
               }
               VerifXVictory();
               VerifOVictory();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseDragged
        // TODO add your handling code here:
        jButton2.setBackground(Color.pink);
    }//GEN-LAST:event_jButton2MouseDragged

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
       // jButton2.setBackground(Color.pink);
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        nextPart();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
